export enum ETileTypeGame {
	CITY = 'CITY',
	EVENT_TILE = 'EVENT_TILE',
	TOURIST_BLUE = 'TOURIST_BLUE',
	CARNIVAL_CITY = 'CARNIVAL_CITY',
	CARNIVAL = 'CARNIVAL',
	TOURIST_PINK = 'TOURIST_PINK',
	START = 'START',
	DESERTED_ISLAND = 'DESERTED_ISLAND',
	WORLD_TOUR = 'WORLD_TOUR',
	TAX = 'TAX',
	CHANCE = 'CHANCE',
}

export enum ETurnStatusGame {
	WAITING_FOR_ROLL = 'WAITING_FOR_ROLL',
	ROLLED_DICE = 'ROLLED_DICE',
	EVALUATING_TILE = 'EVALUATING_TILE',
	HANDLING_EVENT = 'HANDLING_EVENT',
	WAITING_FOR_ACTION = 'WAITING_FOR_ACTION',
	TURN_COMPLETED = 'TURN_COMPLETED',
}
